#ifndef ANIRA_REALTIMESANITIZER_H
#define ANIRA_REALTIMESANITIZER_H

#ifdef ANIRA_WITH_RTSAN
#define ANIRA_REALTIME [[clang::nonblocking]]
#else
#define ANIRA_REALTIME
#endif

#endif //ANIRA_REALTIMESANITIZER_H