# ==============================================================================
# AniraBackends.cmake — prebuilt inference engines for anira
# ==============================================================================
#
# Entry points (called from the top-level CMakeLists):
#   anira_setup_<engine>(<target>)   engine = executorch|libtorch|onnxruntime|tflite|litert
#     Fetches the engine, adds its processor source + USE_<ENGINE> define to <target>,
#     applies its include/link dirs and links it. Defined in cmake/backends/<engine>.cmake.
#     anira_setup_executorch() must run before anira_setup_libtorch() (both bundle XNNPACK).
#
# This file provides what those need:
#   anira_setup_backend(<id>)  download/resolve one engine tree, set ANIRA_<ENGINE>_*:
#     _ROOTDIR _LINKAGE _IS_STATIC _LIB_BASENAME _SHARED_LIB_PATH _VERSION,
#     _STATIC_LIB / _STATIC_LIB_SUBPATH (static), _IOS_SLICE (iOS),
#     EXECUTORCH: _INCLUDE_DIR _COMPILE_DEFINITIONS [_REGISTRATIONS_LIB (Windows)];
#     and BACKEND_BUILD_HEADER_DIRS / BACKEND_BUILD_LIBRARY_DIRS for the caller.
#   anira_target_link_static_backend(<target> <archive>)  on-demand static link with
#     hidden symbols (-load_hidden / --exclude-libs) + the platform system libs.
#   _anira_apply_backend_dirs / _anira_link_backend  small helpers for the per-engine files.
#
# Assets: anira-project/backends release ANIRA_BACKENDS_VERSION, named
#   <libname>-<version>-<OS>-<arch>-<shared|static[-debug]>.zip   (desktop / WASM)
#   <libname>-<version>-Android-<linkage>.zip   (all ABIs under lib/<abi>/)
#   <libname>-<version>-iOS-xcframework.zip     (device + simulator slices, static)
# unpacking to include/ + lib/ (libtorch: its CMake package; iOS: the xcframework).
# Integrity: the asset sha256 published by GitHub is fetched at configure (skipped by
# ANIRA_BACKENDS_SKIP_REMOTE_CHECK / offline / CMake < 3.19); a <dest>.sha256 stamp
# next to the extracted tree triggers a re-download when it differs.
# Linkage follows BUILD_SHARED_LIBS; libtorch is shared-only, executorch static-only,
# WASM and iOS are always static. Static archives are linked on-demand, never
# whole-archive (onnxruntime/tflite carry duplicate protobuf/absl members).
# armv7l (Bela) has no backends asset and uses legacy upstream mirrors.
#
# User overrides (<ENGINE> = LIBTORCH|ONNXRUNTIME|TFLITE|LITERT|EXECUTORCH):
#   ANIRA_BACKENDS_VERSION, ANIRA_BACKENDS_SKIP_REMOTE_CHECK,
#   ANIRA_<ENGINE>_LINKAGE=shared|static, ANIRA_<ENGINE>_ROOTDIR=<tree>,
#   ANIRA_<ENGINE>_URL=... [ANIRA_<ENGINE>_SHA256=...], ANIRA_<ENGINE>_VERSION=...
#   (legacy: LIBTORCH_ROOTDIR, TENSORFLOWLITE_ROOTDIR)
# Bump ANIRA_BACKENDS_VERSION and _anira_engine_version together on a new release.
# ==============================================================================

include_guard(GLOBAL)

get_filename_component(ANIRA_BACKENDS_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
get_filename_component(ANIRA_BACKENDS_MODULES_DIR "${ANIRA_BACKENDS_CMAKE_DIR}/../modules" ABSOLUTE)

if(NOT DEFINED ANIRA_BACKENDS_VERSION OR ANIRA_BACKENDS_VERSION STREQUAL "")
    set(ANIRA_BACKENDS_VERSION "v2.3.0")
endif()

function(_anira_backend_libname id out)
    if(id STREQUAL "libtorch")
        set(${out} "libtorch" PARENT_SCOPE)
    elseif(id STREQUAL "onnxruntime")
        set(${out} "onnxruntime" PARENT_SCOPE)
    elseif(id STREQUAL "tflite")
        set(${out} "tensorflowlite_c" PARENT_SCOPE)
    elseif(id STREQUAL "litert")
        set(${out} "LiteRt" PARENT_SCOPE)
    elseif(id STREQUAL "executorch")
        set(${out} "executorch" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unknown backend id '${id}' (expected libtorch|onnxruntime|tflite|litert|executorch)")
    endif()
endfunction()

function(_anira_engine_version libname out)
    if(libname STREQUAL "libtorch")
        set(${out} "2.12.0" PARENT_SCOPE)
    elseif(libname STREQUAL "onnxruntime")
        set(${out} "1.26.0" PARENT_SCOPE)
    elseif(libname STREQUAL "tensorflowlite_c")
        set(${out} "2.17.0" PARENT_SCOPE)
    elseif(libname STREQUAL "LiteRt")
        set(${out} "2.1.5" PARENT_SCOPE)
    elseif(libname STREQUAL "executorch")
        set(${out} "1.3.1" PARENT_SCOPE)
    else()
        set(${out} "" PARENT_SCOPE)
    endif()
endfunction()

function(_anira_release_json out)
    get_property(_done GLOBAL PROPERTY _ANIRA_RELEASE_JSON_DONE)
    if(_done)
        get_property(_p GLOBAL PROPERTY _ANIRA_RELEASE_JSON_PATH)
        set(${out} "${_p}" PARENT_SCOPE)
        return()
    endif()
    set_property(GLOBAL PROPERTY _ANIRA_RELEASE_JSON_DONE TRUE)
    set_property(GLOBAL PROPERTY _ANIRA_RELEASE_JSON_PATH "")
    set(${out} "" PARENT_SCOPE)

    if(ANIRA_BACKENDS_SKIP_REMOTE_CHECK OR CMAKE_VERSION VERSION_LESS "3.19")
        return()
    endif()

    set(_json "${CMAKE_BINARY_DIR}/anira-backends-release.json")
    set(_hdrs HTTPHEADER "Accept: application/vnd.github+json")
    if(DEFINED ENV{GITHUB_TOKEN} AND NOT "$ENV{GITHUB_TOKEN}" STREQUAL "")
        list(APPEND _hdrs HTTPHEADER "Authorization: Bearer $ENV{GITHUB_TOKEN}")
    endif()
    file(DOWNLOAD
        "https://api.github.com/repos/anira-project/backends/releases/tags/${ANIRA_BACKENDS_VERSION}"
        "${_json}" STATUS _st TIMEOUT 20 ${_hdrs})
    list(GET _st 0 _code)
    if(NOT _code EQUAL 0)
        list(GET _st 1 _m)
        message(STATUS "anira: backend integrity check skipped (release metadata unreachable: ${_m})")
        file(REMOVE "${_json}")
        return()
    endif()
    set_property(GLOBAL PROPERTY _ANIRA_RELEASE_JSON_PATH "${_json}")
    set(${out} "${_json}" PARENT_SCOPE)
endfunction()

function(_anira_asset_digest asset out)
    set(${out} "" PARENT_SCOPE)
    _anira_release_json(_json)
    if(_json STREQUAL "" OR NOT EXISTS "${_json}")
        return()
    endif()
    file(READ "${_json}" _c)
    string(JSON _n ERROR_VARIABLE _e LENGTH "${_c}" assets)
    if(_e OR _n STREQUAL "" OR _n EQUAL 0)
        return()
    endif()
    math(EXPR _last "${_n} - 1")
    foreach(_i RANGE 0 ${_last})
        string(JSON _name ERROR_VARIABLE _e2 GET "${_c}" assets ${_i} name)
        if(_e2)
            continue()
        endif()
        if(_name STREQUAL "${asset}.zip")
            string(JSON _dig ERROR_VARIABLE _e3 GET "${_c}" assets ${_i} digest)
            if(NOT _e3 AND NOT _dig STREQUAL "")
                string(REGEX REPLACE "^sha256:" "" _dig "${_dig}")
                set(${out} "${_dig}" PARENT_SCOPE)
            endif()
            return()
        endif()
    endforeach()
endfunction()

function(_anira_target_tokens out_os out_arch)
    if(EMSDK_VERSION)
        set(${out_os} "WASM" PARENT_SCOPE)
        set(${out_arch} "" PARENT_SCOPE)
        return()
    endif()

    if(CMAKE_SYSTEM_NAME STREQUAL "Android")
        set(${out_os} "Android" PARENT_SCOPE)
        set(${out_arch} "" PARENT_SCOPE)
        return()
    endif()

    if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        set(${out_os} "iOS" PARENT_SCOPE)
        set(${out_arch} "" PARENT_SCOPE)
        return()
    endif()

    if(APPLE)
        if(CMAKE_OSX_ARCHITECTURES MATCHES "arm64" AND CMAKE_OSX_ARCHITECTURES MATCHES "x86_64")
            set(_arch "universal")
        elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "arm64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
            set(_arch "arm64")
        elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
            set(_arch "x86_64")
        else()
            set(_arch "${CMAKE_SYSTEM_PROCESSOR}")
        endif()
        set(${out_os} "macOS" PARENT_SCOPE)
        set(${out_arch} "${_arch}" PARENT_SCOPE)
        return()
    endif()

    if(UNIX)
        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
            set(_arch "aarch64")
        elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "armv7l")
            set(_arch "armv7l")
        else()
            set(_arch "x86_64")
        endif()
        set(${out_os} "Linux" PARENT_SCOPE)
        set(${out_arch} "${_arch}" PARENT_SCOPE)
        return()
    endif()

    if(WIN32)
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|arm64")
            set(_arch "arm64")
        else()
            set(_arch "x86_64")
        endif()
        set(${out_os} "Windows" PARENT_SCOPE)
        set(${out_arch} "${_arch}" PARENT_SCOPE)
        return()
    endif()

    message(FATAL_ERROR "anira backends: unsupported platform")
endfunction()

function(_anira_resolve_linkage id supported out)
    string(TOUPPER "${id}" _ID)

    if(DEFINED ANIRA_${_ID}_LINKAGE AND NOT ANIRA_${_ID}_LINKAGE STREQUAL "")
        set(_linkage "${ANIRA_${_ID}_LINKAGE}")
    elseif(BUILD_SHARED_LIBS)
        set(_linkage "shared")
    else()
        set(_linkage "static")
    endif()

    if(EMSDK_VERSION)
        set(_linkage "static")
    endif()

    if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        set(_linkage "static")
    endif()

    if(NOT _linkage IN_LIST supported)
        if(supported STREQUAL "shared")
            message(STATUS "anira: ${id} ships shared-only — forcing shared linkage (requested '${_linkage}').")
            set(_linkage "shared")
        elseif(supported STREQUAL "static")
            message(STATUS "anira: ${id} ships static-only — forcing static linkage (requested '${_linkage}').")
            set(_linkage "static")
        else()
            message(FATAL_ERROR "anira: ${id} does not support '${_linkage}' linkage (supported: ${supported}).")
        endif()
    endif()

    set(${out} "${_linkage}" PARENT_SCOPE)
endfunction()

function(_anira_download_extract url sha256 dest archive flatten)
    if(EXISTS "${dest}/")
        message(STATUS "anira: backend found at ${dest}")
        return()
    endif()

    file(MAKE_DIRECTORY "${dest}")
    message(STATUS "anira: downloading ${url}")

    set(_zip "${CMAKE_BINARY_DIR}/import/${archive}")
    set(_hash_args "")
    if(NOT sha256 STREQUAL "")
        set(_hash_args EXPECTED_HASH "SHA256=${sha256}")
    endif()

    file(DOWNLOAD "${url}" "${_zip}" STATUS _st SHOW_PROGRESS ${_hash_args})
    list(GET _st 0 _code)
    list(GET _st 1 _msg)

    set(_size 0)
    if(EXISTS "${_zip}")
        file(SIZE "${_zip}" _size)
    endif()
    if(NOT _code EQUAL 0 OR _size LESS 1024)   # file(DOWNLOAD) accepts a 404 HTML body
        file(REMOVE_RECURSE "${dest}")
        file(REMOVE "${_zip}")
        message(FATAL_ERROR "anira: failed to download backend archive.\n  URL: ${url}\n  Reason: ${_msg}")
    endif()

    file(ARCHIVE_EXTRACT INPUT "${_zip}" DESTINATION "${dest}")

    if(flatten)
        string(REGEX REPLACE "\\.(zip|tgz|tar\\.gz)$" "" _stem "${archive}")
        if(EXISTS "${dest}/${_stem}/")
            file(COPY "${dest}/${_stem}/" DESTINATION "${dest}/")
            file(REMOVE_RECURSE "${dest}/${_stem}")
        endif()
    endif()
endfunction()

function(_anira_acquire_backend url asset dest)
    set(_stamp "${dest}.sha256")
    set(_zip "${CMAKE_BINARY_DIR}/import/${asset}.zip")

    _anira_asset_digest("${asset}" _digest)

    set(_reuse FALSE)
    if(EXISTS "${dest}/" AND EXISTS "${_stamp}")
        if(_digest STREQUAL "")
            set(_reuse TRUE)
        else()
            file(READ "${_stamp}" _cached)
            string(STRIP "${_cached}" _cached)
            if(_cached STREQUAL "${_digest}")
                set(_reuse TRUE)
            else()
                message(STATUS "anira: ${asset} changed upstream — re-downloading.")
            endif()
        endif()
    endif()
    if(_reuse)
        message(STATUS "anira: backend ready at ${dest}")
        return()
    endif()

    file(REMOVE_RECURSE "${dest}")
    file(REMOVE "${_stamp}" "${_zip}")
    file(MAKE_DIRECTORY "${dest}")
    message(STATUS "anira: downloading ${url}")

    set(_hash_args "")
    if(NOT _digest STREQUAL "")
        set(_hash_args EXPECTED_HASH "SHA256=${_digest}")
    endif()
    file(DOWNLOAD "${url}" "${_zip}" STATUS _st SHOW_PROGRESS ${_hash_args})
    list(GET _st 0 _code)
    list(GET _st 1 _msg)

    set(_size 0)
    if(EXISTS "${_zip}")
        file(SIZE "${_zip}" _size)
    endif()
    if(NOT _code EQUAL 0 OR _size LESS 1024)
        file(REMOVE_RECURSE "${dest}")
        file(REMOVE "${_zip}")
        message(FATAL_ERROR
            "anira: failed to download backend archive.\n  URL: ${url}\n  Reason: ${_msg}\n"
            "If this platform/linkage is not published, set ANIRA_<ENGINE>_ROOTDIR to a "
            "prebuilt tree or ANIRA_<ENGINE>_URL to a custom build.")
    endif()

    file(ARCHIVE_EXTRACT INPUT "${_zip}" DESTINATION "${dest}")

    if(_digest STREQUAL "")   # stamp written last: marks a fully extracted tree
        file(SHA256 "${_zip}" _digest)
    endif()
    file(WRITE "${_stamp}" "${_digest}\n")
    file(REMOVE "${_zip}")
endfunction()

macro(_anira_setup_legacy_armv7l id)
    set(_la_id "${id}")
    string(TOUPPER "${_la_id}" _LID)
    if(_la_id STREQUAL "libtorch")
        set(_lver "2.5.1")
        set(_dir "${ANIRA_BACKENDS_MODULES_DIR}/libtorch-${_lver}-Linux-armv7l")
        _anira_download_extract(
            "https://github.com/pelinski/bela-torch/releases/download/v${_lver}/pytorch-v${_lver}.tar.gz"
            "" "${_dir}" "pytorch-v${_lver}.tar.gz" TRUE)
        list(APPEND CMAKE_PREFIX_PATH "${_dir}")
        find_package(Torch REQUIRED)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
        set(LIBTORCH_ROOTDIR "${_dir}")
        set(ANIRA_LIBTORCH_ROOTDIR "${_dir}")
        set(ANIRA_LIBTORCH_SHARED_LIB_PATH "${_dir}")
        list(APPEND BACKEND_BUILD_HEADER_DIRS "${_dir}/include")
        list(APPEND BACKEND_BUILD_HEADER_DIRS "${_dir}/include/torch/csrc/api/include")
    elseif(_la_id STREQUAL "onnxruntime")
        set(_lver "1.19.2")
        set(_dir "${ANIRA_BACKENDS_MODULES_DIR}/onnxruntime-${_lver}-Linux-armv7l")
        _anira_download_extract(
            "https://github.com/faressc/onnxruntime-cpp-lib/releases/download/v${_lver}/onnxruntime-${_lver}-Linux-armv7l.tar.gz"
            "" "${_dir}" "onnxruntime-${_lver}-Linux-armv7l.tar.gz" TRUE)
        set(ANIRA_ONNXRUNTIME_ROOTDIR "${_dir}")
        set(ANIRA_ONNXRUNTIME_SHARED_LIB_PATH "${_dir}")
        set(ANIRA_ONNXRUNTIME_LIB_BASENAME "onnxruntime")
        set(ANIRA_ONNXRUNTIME_IS_STATIC FALSE)
        list(APPEND BACKEND_BUILD_HEADER_DIRS "${_dir}/include/onnxruntime")
        list(APPEND BACKEND_BUILD_LIBRARY_DIRS "${_dir}/lib")
    elseif(_la_id STREQUAL "tflite")
        set(_lver "2.17.0")
        set(_dir "${ANIRA_BACKENDS_MODULES_DIR}/tensorflowlite-${_lver}-Linux-armv7l")
        _anira_download_extract(
            "https://github.com/faressc/tflite-c-lib/releases/download/v${_lver}/tensorflowlite_c-${_lver}-Linux-armv7l.zip"
            "" "${_dir}" "tensorflowlite_c-${_lver}-Linux-armv7l.zip" TRUE)
        set(ANIRA_TFLITE_ROOTDIR "${_dir}")
        set(ANIRA_TENSORFLOWLITE_SHARED_LIB_PATH "${_dir}")
        set(ANIRA_TFLITE_LIB_BASENAME "tensorflowlite_c")
        set(ANIRA_TFLITE_IS_STATIC FALSE)
        list(APPEND BACKEND_BUILD_HEADER_DIRS "${_dir}/include")
        list(APPEND BACKEND_BUILD_LIBRARY_DIRS "${_dir}/lib")
    else()
        message(FATAL_ERROR "anira: ${id} has no armv7l (Bela) build.")
    endif()
endmacro()

# ---- fetch + resolve one engine --------------------------------------------
macro(anira_setup_backend id)
    set(_ab_id "${id}")
    string(TOUPPER "${_ab_id}" _ab_ID)
    _anira_backend_libname("${_ab_id}" _ab_libname)

    if(_ab_id STREQUAL "libtorch")
        set(_ab_supported "shared")   # libtorch: shared-only; executorch: static-only
    elseif(_ab_id STREQUAL "executorch")
        set(_ab_supported "static")
    else()
        set(_ab_supported "shared;static")
    endif()
    _anira_resolve_linkage("${_ab_id}" "${_ab_supported}" _ab_linkage)

    set(_ab_byo "")
    if(DEFINED ANIRA_${_ab_ID}_ROOTDIR AND NOT ANIRA_${_ab_ID}_ROOTDIR STREQUAL "")
        set(_ab_byo "${ANIRA_${_ab_ID}_ROOTDIR}")
    elseif(_ab_id STREQUAL "libtorch" AND DEFINED LIBTORCH_ROOTDIR AND NOT LIBTORCH_ROOTDIR STREQUAL "" AND IS_DIRECTORY "${LIBTORCH_ROOTDIR}")
        set(_ab_byo "${LIBTORCH_ROOTDIR}")
    elseif(_ab_id STREQUAL "tflite" AND DEFINED TENSORFLOWLITE_ROOTDIR AND NOT TENSORFLOWLITE_ROOTDIR STREQUAL "" AND IS_DIRECTORY "${TENSORFLOWLITE_ROOTDIR}")
        set(_ab_byo "${TENSORFLOWLITE_ROOTDIR}")
    endif()

    _anira_target_tokens(_ab_os _ab_arch)

    if(NOT _ab_byo STREQUAL "")
        message(STATUS "anira: using bring-your-own ${_ab_id} at ${_ab_byo}")
        set(_ab_rootdir "${_ab_byo}")
    elseif(_ab_arch STREQUAL "armv7l")
        _anira_setup_legacy_armv7l("${_ab_id}")
        set(_ab_rootdir "${ANIRA_${_ab_ID}_ROOTDIR}")
    else()
        if(DEFINED ANIRA_${_ab_ID}_VERSION AND NOT ANIRA_${_ab_ID}_VERSION STREQUAL "")
            set(_ab_version "${ANIRA_${_ab_ID}_VERSION}")
        else()
            _anira_engine_version("${_ab_libname}" _ab_version)
        endif()
        if(_ab_version STREQUAL "")
            message(FATAL_ERROR "anira: no known version for ${_ab_libname}. Set ANIRA_${_ab_ID}_VERSION or ANIRA_${_ab_ID}_ROOTDIR.")
        endif()
        set(ANIRA_${_ab_ID}_VERSION "${_ab_version}")

        set(_ab_linktoken "${_ab_linkage}")
        if(_ab_linkage STREQUAL "static" AND WIN32 AND CMAKE_BUILD_TYPE STREQUAL "Debug"
           AND NOT _ab_id STREQUAL "executorch")
            set(_ab_linktoken "static-debug")
        endif()

        if(_ab_os STREQUAL "WASM")
            set(_ab_asset "${_ab_libname}-${_ab_version}-WASM-${_ab_linktoken}")
        elseif(_ab_os STREQUAL "Android")
            set(_ab_asset "${_ab_libname}-${_ab_version}-Android-${_ab_linktoken}")
        elseif(_ab_os STREQUAL "iOS")
            set(_ab_asset "${_ab_libname}-${_ab_version}-iOS-xcframework")
        else()
            set(_ab_asset "${_ab_libname}-${_ab_version}-${_ab_os}-${_ab_arch}-${_ab_linktoken}")
        endif()

        set(_ab_rootdir "${ANIRA_BACKENDS_MODULES_DIR}/${_ab_asset}")
        if(DEFINED ANIRA_${_ab_ID}_URL AND NOT ANIRA_${_ab_ID}_URL STREQUAL "")
            set(_ab_sha "")
            if(DEFINED ANIRA_${_ab_ID}_SHA256 AND NOT ANIRA_${_ab_ID}_SHA256 STREQUAL "")
                set(_ab_sha "${ANIRA_${_ab_ID}_SHA256}")
            endif()
            _anira_download_extract("${ANIRA_${_ab_ID}_URL}" "${_ab_sha}" "${_ab_rootdir}" "${_ab_asset}.zip" FALSE)
        else()
            set(_ab_url "https://github.com/anira-project/backends/releases/download/${ANIRA_BACKENDS_VERSION}/${_ab_asset}.zip")
            _anira_acquire_backend("${_ab_url}" "${_ab_asset}" "${_ab_rootdir}")
        endif()
    endif()

    if(_ab_id STREQUAL "libtorch")
        if(_ab_byo STREQUAL "" AND NOT _ab_arch STREQUAL "armv7l")
            list(APPEND CMAKE_PREFIX_PATH "${_ab_rootdir}")
            find_package(Torch REQUIRED)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
            list(APPEND BACKEND_BUILD_HEADER_DIRS "${_ab_rootdir}/include")
            list(APPEND BACKEND_BUILD_HEADER_DIRS "${_ab_rootdir}/include/torch/csrc/api/include")
        endif()
        if(TARGET torch)
            target_link_options(torch INTERFACE "-w")
        endif()
        if(TARGET torch_library)
            target_link_options(torch_library INTERFACE "-w")
        endif()
        set(LIBTORCH_ROOTDIR "${_ab_rootdir}")
        set(ANIRA_LIBTORCH_ROOTDIR "${_ab_rootdir}")
        set(ANIRA_LIBTORCH_SHARED_LIB_PATH "${_ab_rootdir}")
        set(ANIRA_LIBTORCH_LINKAGE "shared")
    elseif(_ab_arch STREQUAL "armv7l")
        set(ANIRA_${_ab_ID}_LINKAGE "${_ab_linkage}")
    else()
        if(_ab_linkage STREQUAL "static")
            set(ANIRA_${_ab_ID}_IS_STATIC TRUE)
        else()
            set(ANIRA_${_ab_ID}_IS_STATIC FALSE)
        endif()
        set(ANIRA_${_ab_ID}_ROOTDIR "${_ab_rootdir}")
        set(ANIRA_${_ab_ID}_LINKAGE "${_ab_linkage}")
        set(ANIRA_${_ab_ID}_LIB_BASENAME "${_ab_libname}")
        set(ANIRA_${_ab_ID}_SHARED_LIB_PATH "${_ab_rootdir}")

        if(CMAKE_SYSTEM_NAME STREQUAL "Android")
            set(_ab_incdir "${_ab_rootdir}/include")
            set(_ab_libdir "${_ab_rootdir}/lib/${CMAKE_ANDROID_ARCH_ABI}")
            if(_ab_linkage STREQUAL "static")
                set(ANIRA_${_ab_ID}_STATIC_LIB "${_ab_libdir}/lib${_ab_libname}.a")
                set(ANIRA_${_ab_ID}_STATIC_LIB_SUBPATH "${CMAKE_ANDROID_ARCH_ABI}/lib${_ab_libname}.a")
            endif()
        elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
            if(_ab_id STREQUAL "tflite")
                if(CMAKE_OSX_SYSROOT MATCHES "[Ss]imulator")
                    set(_ab_slice "ios-arm64_x86_64-simulator")
                else()
                    set(_ab_slice "ios-arm64")
                endif()
                set(_ab_fwk "${_ab_rootdir}/TensorFlowLiteC.xcframework/${_ab_slice}/TensorFlowLiteC.framework")
                set(ANIRA_${_ab_ID}_STATIC_LIB "${_ab_fwk}/TensorFlowLiteC")
                set(ANIRA_${_ab_ID}_STATIC_LIB_SUBPATH "TensorFlowLiteC.xcframework/${_ab_slice}/TensorFlowLiteC.framework/TensorFlowLiteC")
                set(ANIRA_${_ab_ID}_IOS_SLICE "${_ab_slice}")
                set(_ab_shim "${CMAKE_BINARY_DIR}/anira-tflite-ios-shim")
                set(ANIRA_${_ab_ID}_IOS_SHIM "${_ab_shim}")
                file(WRITE "${_ab_shim}/tensorflow/lite/c_api.h" "#include <c_api.h>\n")
                file(WRITE "${_ab_shim}/tensorflow/lite/core/c/c_api.h" "#include <c_api.h>\n")
                set(_ab_incdir "${_ab_shim}")
                list(APPEND BACKEND_BUILD_HEADER_DIRS "${_ab_fwk}/Headers")
                set(_ab_libdir "${_ab_fwk}")
            else()
                if(CMAKE_OSX_SYSROOT MATCHES "[Ss]imulator")
                    set(_ab_slice "ios-arm64-simulator")
                else()
                    set(_ab_slice "ios-arm64")
                endif()
                set(_ab_xcfwk "${_ab_rootdir}/${_ab_libname}.xcframework/${_ab_slice}")
                set(_ab_incdir "${_ab_xcfwk}/Headers")
                set(_ab_libdir "${_ab_xcfwk}")
                set(ANIRA_${_ab_ID}_STATIC_LIB "${_ab_xcfwk}/lib${_ab_libname}.a")
                set(ANIRA_${_ab_ID}_STATIC_LIB_SUBPATH "${_ab_libname}.xcframework/${_ab_slice}/lib${_ab_libname}.a")
                set(ANIRA_${_ab_ID}_IOS_SLICE "${_ab_slice}")
            endif()
        else()
            set(_ab_incdir "${_ab_rootdir}/include")
            set(_ab_libdir "${_ab_rootdir}/lib")
            if(_ab_linkage STREQUAL "static")
                if(WIN32)
                    set(ANIRA_${_ab_ID}_STATIC_LIB "${_ab_libdir}/${_ab_libname}.lib")
                    set(ANIRA_${_ab_ID}_STATIC_LIB_SUBPATH "${_ab_libname}.lib")
                else()
                    set(ANIRA_${_ab_ID}_STATIC_LIB "${_ab_libdir}/lib${_ab_libname}.a")
                    set(ANIRA_${_ab_ID}_STATIC_LIB_SUBPATH "lib${_ab_libname}.a")
                endif()
            endif()
        endif()

        if(_ab_id STREQUAL "executorch")
            set(ANIRA_EXECUTORCH_INCLUDE_DIR "${_ab_incdir}")
            set(ANIRA_EXECUTORCH_COMPILE_DEFINITIONS
                C10_USING_CUSTOM_GENERATED_MACROS ET_LOG_ENABLED=0 ET_USE_THREADPOOL)
            if(WIN32)
                set(ANIRA_EXECUTORCH_REGISTRATIONS_LIB "${_ab_libdir}/executorch_registrations.lib")
            endif()
        else()
            list(APPEND BACKEND_BUILD_HEADER_DIRS "${_ab_incdir}")
        endif()
        list(APPEND BACKEND_BUILD_LIBRARY_DIRS "${_ab_libdir}")
    endif()

    message(STATUS "anira: ${id} ready (${_ab_linkage}) at ${_ab_rootdir}")
endmacro()

# ---- link helpers shared by cmake/backends/*.cmake ---------------------------
function(anira_target_link_static_backend target libpath)
    if(EMSDK_VERSION)
        target_link_libraries(${target} PUBLIC "$<BUILD_INTERFACE:${libpath}>")
    elseif(MSVC)
        target_link_libraries(${target} PUBLIC "$<BUILD_INTERFACE:${libpath}>")
    elseif(APPLE)   # -load_hidden / --exclude-libs: keep backend symbols out of the plugin's exports
        target_link_libraries(${target} PUBLIC
            "$<BUILD_INTERFACE:-Wl,-load_hidden,${libpath}>" "-framework Foundation" "-framework CoreFoundation" "-framework Metal")
    elseif(ANDROID)
        get_filename_component(_anira_backend_archive "${libpath}" NAME)
        target_link_options(${target} PUBLIC "LINKER:--exclude-libs,${_anira_backend_archive}")
        target_link_libraries(${target} PUBLIC "$<BUILD_INTERFACE:${libpath}>" EGL GLESv2 android log)
    else()
        find_package(Threads REQUIRED)
        get_filename_component(_anira_backend_archive "${libpath}" NAME)
        target_link_options(${target} PUBLIC "LINKER:--exclude-libs,${_anira_backend_archive}")
        target_link_libraries(${target} PUBLIC
            "$<BUILD_INTERFACE:${libpath}>" Threads::Threads ${CMAKE_DL_LIBS} m)
    endif()
endfunction()

macro(_anira_apply_backend_dirs target)
    foreach(_ab_dir ${BACKEND_BUILD_HEADER_DIRS})
        target_include_directories(${target} SYSTEM PUBLIC $<BUILD_INTERFACE:${_ab_dir}>)
    endforeach()
    foreach(_ab_dir ${BACKEND_BUILD_LIBRARY_DIRS})
        target_link_directories(${target} PUBLIC $<BUILD_INTERFACE:${_ab_dir}>)
    endforeach()
    set(BACKEND_BUILD_HEADER_DIRS)
    set(BACKEND_BUILD_LIBRARY_DIRS)
endmacro()

macro(_anira_link_backend target ID shared_target)
    if(ANIRA_${ID}_IS_STATIC)
        anira_target_link_static_backend(${target} "${ANIRA_${ID}_STATIC_LIB}")
    else()
        target_link_libraries(${target} PUBLIC ${shared_target})
    endif()
endmacro()

# ---- anira_setup_<engine>(<target>) ------------------------------------------
include(${CMAKE_CURRENT_LIST_DIR}/backends/executorch.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/backends/libtorch.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/backends/onnxruntime.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/backends/tflite.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/backends/litert.cmake)
